// Generated by utils/GenerateHighwayOps.swift. Do not edit.

#ifndef SWIFT_HIGHWAY_OPS_H
#define SWIFT_HIGHWAY_OPS_H

#include <stddef.h>
#include <stdint.h>

// HWY_DISABLED_TARGETS is set by the build, see Package.swift.
#include "hwy/highway.h"

namespace HighwayOps {
namespace hn = hwy::HWY_NAMESPACE;

/// Whether the static target only emulates vectors, in which case a caller is better off
/// with its own scalar code.
HWY_INLINE bool isEmulated() {
  return HWY_TARGET == HWY_SCALAR || HWY_TARGET == HWY_EMU128;
}

/// The name of the target the ops below were compiled for.
HWY_INLINE const char* targetName() { return hwy::TargetName(HWY_TARGET); }

using TagU8 = hn::ScalableTag<uint8_t>;
using VectorU8 = hn::VFromD<TagU8>;
using MaskU8 = hn::MFromD<TagU8>;
HWY_INLINE size_t laneCountU8() { return hn::Lanes(TagU8()); }
HWY_INLINE VectorU8 zeroU8() { return hn::Zero(TagU8()); }
HWY_INLINE VectorU8 repeatingU8(uint8_t value) { return hn::Set(TagU8(), value); }
HWY_INLINE VectorU8 iotaU8(uint8_t value) { return hn::Iota(TagU8(), value); }
HWY_INLINE VectorU8 loadU8(const uint8_t* from) { return hn::LoadU(TagU8(), from); }
HWY_INLINE VectorU8 loadAlignedU8(const uint8_t* from) { return hn::Load(TagU8(), from); }
HWY_INLINE VectorU8 loadFirstU8(const uint8_t* from, size_t count) { return hn::LoadN(TagU8(), from, count); }
HWY_INLINE void storeU8(VectorU8 a, uint8_t* to) { hn::StoreU(a, TagU8(), to); }
HWY_INLINE void storeAlignedU8(VectorU8 a, uint8_t* to) { hn::Store(a, TagU8(), to); }
HWY_INLINE void storeFirstU8(VectorU8 a, uint8_t* to, size_t count) { hn::StoreN(a, TagU8(), to, count); }
HWY_INLINE VectorU8 addingU8(VectorU8 a, VectorU8 b) { return hn::Add(a, b); }
HWY_INLINE VectorU8 subtractingU8(VectorU8 a, VectorU8 b) { return hn::Sub(a, b); }
HWY_INLINE VectorU8 minimumU8(VectorU8 a, VectorU8 b) { return hn::Min(a, b); }
HWY_INLINE VectorU8 maximumU8(VectorU8 a, VectorU8 b) { return hn::Max(a, b); }
HWY_INLINE VectorU8 saturatingAddingU8(VectorU8 a, VectorU8 b) { return hn::SaturatedAdd(a, b); }
HWY_INLINE VectorU8 saturatingSubtractingU8(VectorU8 a, VectorU8 b) { return hn::SaturatedSub(a, b); }
HWY_INLINE VectorU8 roundedAverageU8(VectorU8 a, VectorU8 b) { return hn::AverageRound(a, b); }
HWY_INLINE VectorU8 bitwiseAndU8(VectorU8 a, VectorU8 b) { return hn::And(a, b); }
HWY_INLINE VectorU8 bitwiseOrU8(VectorU8 a, VectorU8 b) { return hn::Or(a, b); }
HWY_INLINE VectorU8 bitwiseXorU8(VectorU8 a, VectorU8 b) { return hn::Xor(a, b); }
HWY_INLINE VectorU8 bitwiseNotU8(VectorU8 a) { return hn::Not(a); }
HWY_INLINE VectorU8 bitwiseAndNotU8(VectorU8 a, VectorU8 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorU8 shiftedLeftU8(VectorU8 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorU8 shiftedRightU8(VectorU8 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskU8 equalToU8(VectorU8 a, VectorU8 b) { return hn::Eq(a, b); }
HWY_INLINE MaskU8 notEqualToU8(VectorU8 a, VectorU8 b) { return hn::Ne(a, b); }
HWY_INLINE MaskU8 lessThanU8(VectorU8 a, VectorU8 b) { return hn::Lt(a, b); }
HWY_INLINE MaskU8 greaterThanU8(VectorU8 a, VectorU8 b) { return hn::Gt(a, b); }
HWY_INLINE VectorU8 selectingU8(MaskU8 mask, VectorU8 a, VectorU8 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorU8 selectingOrZeroU8(MaskU8 mask, VectorU8 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorU8 zeroingSelectedU8(MaskU8 mask, VectorU8 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskU8 firstLanesU8(size_t count) { return hn::FirstN(TagU8(), count); }
HWY_INLINE bool allTrueU8(MaskU8 mask) { return hn::AllTrue(TagU8(), mask); }
HWY_INLINE bool allFalseU8(MaskU8 mask) { return hn::AllFalse(TagU8(), mask); }
HWY_INLINE size_t trueCountU8(MaskU8 mask) { return hn::CountTrue(TagU8(), mask); }
HWY_INLINE intptr_t firstTrueIndexU8(MaskU8 mask) { return hn::FindFirstTrue(TagU8(), mask); }
HWY_INLINE uint8_t firstLaneU8(VectorU8 a) { return hn::GetLane(a); }
HWY_INLINE VectorU8 reversedU8(VectorU8 a) { return hn::Reverse(TagU8(), a); }
HWY_INLINE VectorU8 tableLookupBytesU8(VectorU8 a, VectorU8 b) { return hn::TableLookupBytes(a, b); }
HWY_INLINE void loadInterleaved2U8(const uint8_t* from, VectorU8& v0, VectorU8& v1) { hn::LoadInterleaved2(TagU8(), from, v0, v1); }
HWY_INLINE void loadInterleaved3U8(const uint8_t* from, VectorU8& v0, VectorU8& v1, VectorU8& v2) { hn::LoadInterleaved3(TagU8(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4U8(const uint8_t* from, VectorU8& v0, VectorU8& v1, VectorU8& v2, VectorU8& v3) { hn::LoadInterleaved4(TagU8(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2U8(VectorU8 a, VectorU8 b, uint8_t* to) { hn::StoreInterleaved2(a, b, TagU8(), to); }
HWY_INLINE void storeInterleaved3U8(VectorU8 a, VectorU8 b, VectorU8 c, uint8_t* to) { hn::StoreInterleaved3(a, b, c, TagU8(), to); }
HWY_INLINE void storeInterleaved4U8(VectorU8 a, VectorU8 b, VectorU8 c, VectorU8 d, uint8_t* to) { hn::StoreInterleaved4(a, b, c, d, TagU8(), to); }

using TagU16 = hn::ScalableTag<uint16_t>;
using VectorU16 = hn::VFromD<TagU16>;
using MaskU16 = hn::MFromD<TagU16>;
HWY_INLINE size_t laneCountU16() { return hn::Lanes(TagU16()); }
HWY_INLINE VectorU16 zeroU16() { return hn::Zero(TagU16()); }
HWY_INLINE VectorU16 repeatingU16(uint16_t value) { return hn::Set(TagU16(), value); }
HWY_INLINE VectorU16 iotaU16(uint16_t value) { return hn::Iota(TagU16(), value); }
HWY_INLINE VectorU16 loadU16(const uint16_t* from) { return hn::LoadU(TagU16(), from); }
HWY_INLINE VectorU16 loadAlignedU16(const uint16_t* from) { return hn::Load(TagU16(), from); }
HWY_INLINE VectorU16 loadFirstU16(const uint16_t* from, size_t count) { return hn::LoadN(TagU16(), from, count); }
HWY_INLINE void storeU16(VectorU16 a, uint16_t* to) { hn::StoreU(a, TagU16(), to); }
HWY_INLINE void storeAlignedU16(VectorU16 a, uint16_t* to) { hn::Store(a, TagU16(), to); }
HWY_INLINE void storeFirstU16(VectorU16 a, uint16_t* to, size_t count) { hn::StoreN(a, TagU16(), to, count); }
HWY_INLINE VectorU16 addingU16(VectorU16 a, VectorU16 b) { return hn::Add(a, b); }
HWY_INLINE VectorU16 subtractingU16(VectorU16 a, VectorU16 b) { return hn::Sub(a, b); }
HWY_INLINE VectorU16 multiplyingU16(VectorU16 a, VectorU16 b) { return hn::Mul(a, b); }
HWY_INLINE VectorU16 minimumU16(VectorU16 a, VectorU16 b) { return hn::Min(a, b); }
HWY_INLINE VectorU16 maximumU16(VectorU16 a, VectorU16 b) { return hn::Max(a, b); }
HWY_INLINE VectorU16 saturatingAddingU16(VectorU16 a, VectorU16 b) { return hn::SaturatedAdd(a, b); }
HWY_INLINE VectorU16 saturatingSubtractingU16(VectorU16 a, VectorU16 b) { return hn::SaturatedSub(a, b); }
HWY_INLINE VectorU16 roundedAverageU16(VectorU16 a, VectorU16 b) { return hn::AverageRound(a, b); }
HWY_INLINE VectorU16 bitwiseAndU16(VectorU16 a, VectorU16 b) { return hn::And(a, b); }
HWY_INLINE VectorU16 bitwiseOrU16(VectorU16 a, VectorU16 b) { return hn::Or(a, b); }
HWY_INLINE VectorU16 bitwiseXorU16(VectorU16 a, VectorU16 b) { return hn::Xor(a, b); }
HWY_INLINE VectorU16 bitwiseNotU16(VectorU16 a) { return hn::Not(a); }
HWY_INLINE VectorU16 bitwiseAndNotU16(VectorU16 a, VectorU16 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorU16 shiftedLeftU16(VectorU16 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorU16 shiftedRightU16(VectorU16 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskU16 equalToU16(VectorU16 a, VectorU16 b) { return hn::Eq(a, b); }
HWY_INLINE MaskU16 notEqualToU16(VectorU16 a, VectorU16 b) { return hn::Ne(a, b); }
HWY_INLINE MaskU16 lessThanU16(VectorU16 a, VectorU16 b) { return hn::Lt(a, b); }
HWY_INLINE MaskU16 greaterThanU16(VectorU16 a, VectorU16 b) { return hn::Gt(a, b); }
HWY_INLINE VectorU16 selectingU16(MaskU16 mask, VectorU16 a, VectorU16 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorU16 selectingOrZeroU16(MaskU16 mask, VectorU16 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorU16 zeroingSelectedU16(MaskU16 mask, VectorU16 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskU16 firstLanesU16(size_t count) { return hn::FirstN(TagU16(), count); }
HWY_INLINE bool allTrueU16(MaskU16 mask) { return hn::AllTrue(TagU16(), mask); }
HWY_INLINE bool allFalseU16(MaskU16 mask) { return hn::AllFalse(TagU16(), mask); }
HWY_INLINE size_t trueCountU16(MaskU16 mask) { return hn::CountTrue(TagU16(), mask); }
HWY_INLINE intptr_t firstTrueIndexU16(MaskU16 mask) { return hn::FindFirstTrue(TagU16(), mask); }
HWY_INLINE uint16_t sumU16(VectorU16 a) { return hn::ReduceSum(TagU16(), a); }
HWY_INLINE uint16_t smallestU16(VectorU16 a) { return hn::ReduceMin(TagU16(), a); }
HWY_INLINE uint16_t largestU16(VectorU16 a) { return hn::ReduceMax(TagU16(), a); }
HWY_INLINE uint16_t firstLaneU16(VectorU16 a) { return hn::GetLane(a); }
HWY_INLINE VectorU16 reversedU16(VectorU16 a) { return hn::Reverse(TagU16(), a); }
HWY_INLINE void loadInterleaved2U16(const uint16_t* from, VectorU16& v0, VectorU16& v1) { hn::LoadInterleaved2(TagU16(), from, v0, v1); }
HWY_INLINE void loadInterleaved3U16(const uint16_t* from, VectorU16& v0, VectorU16& v1, VectorU16& v2) { hn::LoadInterleaved3(TagU16(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4U16(const uint16_t* from, VectorU16& v0, VectorU16& v1, VectorU16& v2, VectorU16& v3) { hn::LoadInterleaved4(TagU16(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2U16(VectorU16 a, VectorU16 b, uint16_t* to) { hn::StoreInterleaved2(a, b, TagU16(), to); }
HWY_INLINE void storeInterleaved3U16(VectorU16 a, VectorU16 b, VectorU16 c, uint16_t* to) { hn::StoreInterleaved3(a, b, c, TagU16(), to); }
HWY_INLINE void storeInterleaved4U16(VectorU16 a, VectorU16 b, VectorU16 c, VectorU16 d, uint16_t* to) { hn::StoreInterleaved4(a, b, c, d, TagU16(), to); }
HWY_INLINE VectorU16 loadWideningU8ToU16(const uint8_t* from) { return hn::PromoteTo(TagU16(), hn::LoadU(hn::Rebind<uint8_t, TagU16>(), from)); }
HWY_INLINE VectorU16 loadFirstWideningU8ToU16(const uint8_t* from, size_t count) { return hn::PromoteTo(TagU16(), hn::LoadN(hn::Rebind<uint8_t, TagU16>(), from, count)); }

using TagU32 = hn::ScalableTag<uint32_t>;
using VectorU32 = hn::VFromD<TagU32>;
using MaskU32 = hn::MFromD<TagU32>;
HWY_INLINE size_t laneCountU32() { return hn::Lanes(TagU32()); }
HWY_INLINE VectorU32 zeroU32() { return hn::Zero(TagU32()); }
HWY_INLINE VectorU32 repeatingU32(uint32_t value) { return hn::Set(TagU32(), value); }
HWY_INLINE VectorU32 iotaU32(uint32_t value) { return hn::Iota(TagU32(), value); }
HWY_INLINE VectorU32 loadU32(const uint32_t* from) { return hn::LoadU(TagU32(), from); }
HWY_INLINE VectorU32 loadAlignedU32(const uint32_t* from) { return hn::Load(TagU32(), from); }
HWY_INLINE VectorU32 loadFirstU32(const uint32_t* from, size_t count) { return hn::LoadN(TagU32(), from, count); }
HWY_INLINE void storeU32(VectorU32 a, uint32_t* to) { hn::StoreU(a, TagU32(), to); }
HWY_INLINE void storeAlignedU32(VectorU32 a, uint32_t* to) { hn::Store(a, TagU32(), to); }
HWY_INLINE void storeFirstU32(VectorU32 a, uint32_t* to, size_t count) { hn::StoreN(a, TagU32(), to, count); }
HWY_INLINE VectorU32 addingU32(VectorU32 a, VectorU32 b) { return hn::Add(a, b); }
HWY_INLINE VectorU32 subtractingU32(VectorU32 a, VectorU32 b) { return hn::Sub(a, b); }
HWY_INLINE VectorU32 multiplyingU32(VectorU32 a, VectorU32 b) { return hn::Mul(a, b); }
HWY_INLINE VectorU32 minimumU32(VectorU32 a, VectorU32 b) { return hn::Min(a, b); }
HWY_INLINE VectorU32 maximumU32(VectorU32 a, VectorU32 b) { return hn::Max(a, b); }
HWY_INLINE VectorU32 bitwiseAndU32(VectorU32 a, VectorU32 b) { return hn::And(a, b); }
HWY_INLINE VectorU32 bitwiseOrU32(VectorU32 a, VectorU32 b) { return hn::Or(a, b); }
HWY_INLINE VectorU32 bitwiseXorU32(VectorU32 a, VectorU32 b) { return hn::Xor(a, b); }
HWY_INLINE VectorU32 bitwiseNotU32(VectorU32 a) { return hn::Not(a); }
HWY_INLINE VectorU32 bitwiseAndNotU32(VectorU32 a, VectorU32 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorU32 shiftedLeftU32(VectorU32 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorU32 shiftedRightU32(VectorU32 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskU32 equalToU32(VectorU32 a, VectorU32 b) { return hn::Eq(a, b); }
HWY_INLINE MaskU32 notEqualToU32(VectorU32 a, VectorU32 b) { return hn::Ne(a, b); }
HWY_INLINE MaskU32 lessThanU32(VectorU32 a, VectorU32 b) { return hn::Lt(a, b); }
HWY_INLINE MaskU32 greaterThanU32(VectorU32 a, VectorU32 b) { return hn::Gt(a, b); }
HWY_INLINE VectorU32 selectingU32(MaskU32 mask, VectorU32 a, VectorU32 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorU32 selectingOrZeroU32(MaskU32 mask, VectorU32 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorU32 zeroingSelectedU32(MaskU32 mask, VectorU32 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskU32 firstLanesU32(size_t count) { return hn::FirstN(TagU32(), count); }
HWY_INLINE bool allTrueU32(MaskU32 mask) { return hn::AllTrue(TagU32(), mask); }
HWY_INLINE bool allFalseU32(MaskU32 mask) { return hn::AllFalse(TagU32(), mask); }
HWY_INLINE size_t trueCountU32(MaskU32 mask) { return hn::CountTrue(TagU32(), mask); }
HWY_INLINE intptr_t firstTrueIndexU32(MaskU32 mask) { return hn::FindFirstTrue(TagU32(), mask); }
HWY_INLINE uint32_t sumU32(VectorU32 a) { return hn::ReduceSum(TagU32(), a); }
HWY_INLINE uint32_t smallestU32(VectorU32 a) { return hn::ReduceMin(TagU32(), a); }
HWY_INLINE uint32_t largestU32(VectorU32 a) { return hn::ReduceMax(TagU32(), a); }
HWY_INLINE uint32_t firstLaneU32(VectorU32 a) { return hn::GetLane(a); }
HWY_INLINE VectorU32 reversedU32(VectorU32 a) { return hn::Reverse(TagU32(), a); }
HWY_INLINE void loadInterleaved2U32(const uint32_t* from, VectorU32& v0, VectorU32& v1) { hn::LoadInterleaved2(TagU32(), from, v0, v1); }
HWY_INLINE void loadInterleaved3U32(const uint32_t* from, VectorU32& v0, VectorU32& v1, VectorU32& v2) { hn::LoadInterleaved3(TagU32(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4U32(const uint32_t* from, VectorU32& v0, VectorU32& v1, VectorU32& v2, VectorU32& v3) { hn::LoadInterleaved4(TagU32(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2U32(VectorU32 a, VectorU32 b, uint32_t* to) { hn::StoreInterleaved2(a, b, TagU32(), to); }
HWY_INLINE void storeInterleaved3U32(VectorU32 a, VectorU32 b, VectorU32 c, uint32_t* to) { hn::StoreInterleaved3(a, b, c, TagU32(), to); }
HWY_INLINE void storeInterleaved4U32(VectorU32 a, VectorU32 b, VectorU32 c, VectorU32 d, uint32_t* to) { hn::StoreInterleaved4(a, b, c, d, TagU32(), to); }
HWY_INLINE VectorU32 loadWideningU8ToU32(const uint8_t* from) { return hn::PromoteTo(TagU32(), hn::LoadU(hn::Rebind<uint8_t, TagU32>(), from)); }
HWY_INLINE VectorU32 loadWideningU16ToU32(const uint16_t* from) { return hn::PromoteTo(TagU32(), hn::LoadU(hn::Rebind<uint16_t, TagU32>(), from)); }
HWY_INLINE VectorU32 loadFirstWideningU8ToU32(const uint8_t* from, size_t count) { return hn::PromoteTo(TagU32(), hn::LoadN(hn::Rebind<uint8_t, TagU32>(), from, count)); }
HWY_INLINE VectorU32 loadFirstWideningU16ToU32(const uint16_t* from, size_t count) { return hn::PromoteTo(TagU32(), hn::LoadN(hn::Rebind<uint16_t, TagU32>(), from, count)); }

using TagU64 = hn::ScalableTag<uint64_t>;
using VectorU64 = hn::VFromD<TagU64>;
using MaskU64 = hn::MFromD<TagU64>;
HWY_INLINE size_t laneCountU64() { return hn::Lanes(TagU64()); }
HWY_INLINE VectorU64 zeroU64() { return hn::Zero(TagU64()); }
HWY_INLINE VectorU64 repeatingU64(uint64_t value) { return hn::Set(TagU64(), value); }
HWY_INLINE VectorU64 iotaU64(uint64_t value) { return hn::Iota(TagU64(), value); }
HWY_INLINE VectorU64 loadU64(const uint64_t* from) { return hn::LoadU(TagU64(), from); }
HWY_INLINE VectorU64 loadAlignedU64(const uint64_t* from) { return hn::Load(TagU64(), from); }
HWY_INLINE VectorU64 loadFirstU64(const uint64_t* from, size_t count) { return hn::LoadN(TagU64(), from, count); }
HWY_INLINE void storeU64(VectorU64 a, uint64_t* to) { hn::StoreU(a, TagU64(), to); }
HWY_INLINE void storeAlignedU64(VectorU64 a, uint64_t* to) { hn::Store(a, TagU64(), to); }
HWY_INLINE void storeFirstU64(VectorU64 a, uint64_t* to, size_t count) { hn::StoreN(a, TagU64(), to, count); }
HWY_INLINE VectorU64 addingU64(VectorU64 a, VectorU64 b) { return hn::Add(a, b); }
HWY_INLINE VectorU64 subtractingU64(VectorU64 a, VectorU64 b) { return hn::Sub(a, b); }
HWY_INLINE VectorU64 multiplyingU64(VectorU64 a, VectorU64 b) { return hn::Mul(a, b); }
HWY_INLINE VectorU64 minimumU64(VectorU64 a, VectorU64 b) { return hn::Min(a, b); }
HWY_INLINE VectorU64 maximumU64(VectorU64 a, VectorU64 b) { return hn::Max(a, b); }
HWY_INLINE VectorU64 bitwiseAndU64(VectorU64 a, VectorU64 b) { return hn::And(a, b); }
HWY_INLINE VectorU64 bitwiseOrU64(VectorU64 a, VectorU64 b) { return hn::Or(a, b); }
HWY_INLINE VectorU64 bitwiseXorU64(VectorU64 a, VectorU64 b) { return hn::Xor(a, b); }
HWY_INLINE VectorU64 bitwiseNotU64(VectorU64 a) { return hn::Not(a); }
HWY_INLINE VectorU64 bitwiseAndNotU64(VectorU64 a, VectorU64 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorU64 shiftedLeftU64(VectorU64 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorU64 shiftedRightU64(VectorU64 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskU64 equalToU64(VectorU64 a, VectorU64 b) { return hn::Eq(a, b); }
HWY_INLINE MaskU64 notEqualToU64(VectorU64 a, VectorU64 b) { return hn::Ne(a, b); }
HWY_INLINE MaskU64 lessThanU64(VectorU64 a, VectorU64 b) { return hn::Lt(a, b); }
HWY_INLINE MaskU64 greaterThanU64(VectorU64 a, VectorU64 b) { return hn::Gt(a, b); }
HWY_INLINE VectorU64 selectingU64(MaskU64 mask, VectorU64 a, VectorU64 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorU64 selectingOrZeroU64(MaskU64 mask, VectorU64 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorU64 zeroingSelectedU64(MaskU64 mask, VectorU64 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskU64 firstLanesU64(size_t count) { return hn::FirstN(TagU64(), count); }
HWY_INLINE bool allTrueU64(MaskU64 mask) { return hn::AllTrue(TagU64(), mask); }
HWY_INLINE bool allFalseU64(MaskU64 mask) { return hn::AllFalse(TagU64(), mask); }
HWY_INLINE size_t trueCountU64(MaskU64 mask) { return hn::CountTrue(TagU64(), mask); }
HWY_INLINE intptr_t firstTrueIndexU64(MaskU64 mask) { return hn::FindFirstTrue(TagU64(), mask); }
HWY_INLINE uint64_t sumU64(VectorU64 a) { return hn::ReduceSum(TagU64(), a); }
HWY_INLINE uint64_t smallestU64(VectorU64 a) { return hn::ReduceMin(TagU64(), a); }
HWY_INLINE uint64_t largestU64(VectorU64 a) { return hn::ReduceMax(TagU64(), a); }
HWY_INLINE uint64_t firstLaneU64(VectorU64 a) { return hn::GetLane(a); }
HWY_INLINE VectorU64 reversedU64(VectorU64 a) { return hn::Reverse(TagU64(), a); }
HWY_INLINE void loadInterleaved2U64(const uint64_t* from, VectorU64& v0, VectorU64& v1) { hn::LoadInterleaved2(TagU64(), from, v0, v1); }
HWY_INLINE void loadInterleaved3U64(const uint64_t* from, VectorU64& v0, VectorU64& v1, VectorU64& v2) { hn::LoadInterleaved3(TagU64(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4U64(const uint64_t* from, VectorU64& v0, VectorU64& v1, VectorU64& v2, VectorU64& v3) { hn::LoadInterleaved4(TagU64(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2U64(VectorU64 a, VectorU64 b, uint64_t* to) { hn::StoreInterleaved2(a, b, TagU64(), to); }
HWY_INLINE void storeInterleaved3U64(VectorU64 a, VectorU64 b, VectorU64 c, uint64_t* to) { hn::StoreInterleaved3(a, b, c, TagU64(), to); }
HWY_INLINE void storeInterleaved4U64(VectorU64 a, VectorU64 b, VectorU64 c, VectorU64 d, uint64_t* to) { hn::StoreInterleaved4(a, b, c, d, TagU64(), to); }
HWY_INLINE VectorU64 loadWideningU8ToU64(const uint8_t* from) { return hn::PromoteTo(TagU64(), hn::LoadU(hn::Rebind<uint8_t, TagU64>(), from)); }
HWY_INLINE VectorU64 loadWideningU16ToU64(const uint16_t* from) { return hn::PromoteTo(TagU64(), hn::LoadU(hn::Rebind<uint16_t, TagU64>(), from)); }
HWY_INLINE VectorU64 loadWideningU32ToU64(const uint32_t* from) { return hn::PromoteTo(TagU64(), hn::LoadU(hn::Rebind<uint32_t, TagU64>(), from)); }
HWY_INLINE VectorU64 loadFirstWideningU8ToU64(const uint8_t* from, size_t count) { return hn::PromoteTo(TagU64(), hn::LoadN(hn::Rebind<uint8_t, TagU64>(), from, count)); }
HWY_INLINE VectorU64 loadFirstWideningU16ToU64(const uint16_t* from, size_t count) { return hn::PromoteTo(TagU64(), hn::LoadN(hn::Rebind<uint16_t, TagU64>(), from, count)); }
HWY_INLINE VectorU64 loadFirstWideningU32ToU64(const uint32_t* from, size_t count) { return hn::PromoteTo(TagU64(), hn::LoadN(hn::Rebind<uint32_t, TagU64>(), from, count)); }

using TagI8 = hn::ScalableTag<int8_t>;
using VectorI8 = hn::VFromD<TagI8>;
using MaskI8 = hn::MFromD<TagI8>;
HWY_INLINE size_t laneCountI8() { return hn::Lanes(TagI8()); }
HWY_INLINE VectorI8 zeroI8() { return hn::Zero(TagI8()); }
HWY_INLINE VectorI8 repeatingI8(int8_t value) { return hn::Set(TagI8(), value); }
HWY_INLINE VectorI8 iotaI8(int8_t value) { return hn::Iota(TagI8(), value); }
HWY_INLINE VectorI8 loadI8(const int8_t* from) { return hn::LoadU(TagI8(), from); }
HWY_INLINE VectorI8 loadAlignedI8(const int8_t* from) { return hn::Load(TagI8(), from); }
HWY_INLINE VectorI8 loadFirstI8(const int8_t* from, size_t count) { return hn::LoadN(TagI8(), from, count); }
HWY_INLINE void storeI8(VectorI8 a, int8_t* to) { hn::StoreU(a, TagI8(), to); }
HWY_INLINE void storeAlignedI8(VectorI8 a, int8_t* to) { hn::Store(a, TagI8(), to); }
HWY_INLINE void storeFirstI8(VectorI8 a, int8_t* to, size_t count) { hn::StoreN(a, TagI8(), to, count); }
HWY_INLINE VectorI8 addingI8(VectorI8 a, VectorI8 b) { return hn::Add(a, b); }
HWY_INLINE VectorI8 subtractingI8(VectorI8 a, VectorI8 b) { return hn::Sub(a, b); }
HWY_INLINE VectorI8 minimumI8(VectorI8 a, VectorI8 b) { return hn::Min(a, b); }
HWY_INLINE VectorI8 maximumI8(VectorI8 a, VectorI8 b) { return hn::Max(a, b); }
HWY_INLINE VectorI8 negatedI8(VectorI8 a) { return hn::Neg(a); }
HWY_INLINE VectorI8 magnitudeI8(VectorI8 a) { return hn::Abs(a); }
HWY_INLINE VectorI8 saturatingAddingI8(VectorI8 a, VectorI8 b) { return hn::SaturatedAdd(a, b); }
HWY_INLINE VectorI8 saturatingSubtractingI8(VectorI8 a, VectorI8 b) { return hn::SaturatedSub(a, b); }
HWY_INLINE VectorI8 bitwiseAndI8(VectorI8 a, VectorI8 b) { return hn::And(a, b); }
HWY_INLINE VectorI8 bitwiseOrI8(VectorI8 a, VectorI8 b) { return hn::Or(a, b); }
HWY_INLINE VectorI8 bitwiseXorI8(VectorI8 a, VectorI8 b) { return hn::Xor(a, b); }
HWY_INLINE VectorI8 bitwiseNotI8(VectorI8 a) { return hn::Not(a); }
HWY_INLINE VectorI8 bitwiseAndNotI8(VectorI8 a, VectorI8 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorI8 shiftedLeftI8(VectorI8 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorI8 shiftedRightI8(VectorI8 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskI8 equalToI8(VectorI8 a, VectorI8 b) { return hn::Eq(a, b); }
HWY_INLINE MaskI8 notEqualToI8(VectorI8 a, VectorI8 b) { return hn::Ne(a, b); }
HWY_INLINE MaskI8 lessThanI8(VectorI8 a, VectorI8 b) { return hn::Lt(a, b); }
HWY_INLINE MaskI8 greaterThanI8(VectorI8 a, VectorI8 b) { return hn::Gt(a, b); }
HWY_INLINE VectorI8 selectingI8(MaskI8 mask, VectorI8 a, VectorI8 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorI8 selectingOrZeroI8(MaskI8 mask, VectorI8 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorI8 zeroingSelectedI8(MaskI8 mask, VectorI8 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskI8 firstLanesI8(size_t count) { return hn::FirstN(TagI8(), count); }
HWY_INLINE bool allTrueI8(MaskI8 mask) { return hn::AllTrue(TagI8(), mask); }
HWY_INLINE bool allFalseI8(MaskI8 mask) { return hn::AllFalse(TagI8(), mask); }
HWY_INLINE size_t trueCountI8(MaskI8 mask) { return hn::CountTrue(TagI8(), mask); }
HWY_INLINE intptr_t firstTrueIndexI8(MaskI8 mask) { return hn::FindFirstTrue(TagI8(), mask); }
HWY_INLINE int8_t firstLaneI8(VectorI8 a) { return hn::GetLane(a); }
HWY_INLINE VectorI8 reversedI8(VectorI8 a) { return hn::Reverse(TagI8(), a); }
HWY_INLINE VectorI8 tableLookupBytesI8(VectorI8 a, VectorI8 b) { return hn::TableLookupBytes(a, b); }
HWY_INLINE void loadInterleaved2I8(const int8_t* from, VectorI8& v0, VectorI8& v1) { hn::LoadInterleaved2(TagI8(), from, v0, v1); }
HWY_INLINE void loadInterleaved3I8(const int8_t* from, VectorI8& v0, VectorI8& v1, VectorI8& v2) { hn::LoadInterleaved3(TagI8(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4I8(const int8_t* from, VectorI8& v0, VectorI8& v1, VectorI8& v2, VectorI8& v3) { hn::LoadInterleaved4(TagI8(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2I8(VectorI8 a, VectorI8 b, int8_t* to) { hn::StoreInterleaved2(a, b, TagI8(), to); }
HWY_INLINE void storeInterleaved3I8(VectorI8 a, VectorI8 b, VectorI8 c, int8_t* to) { hn::StoreInterleaved3(a, b, c, TagI8(), to); }
HWY_INLINE void storeInterleaved4I8(VectorI8 a, VectorI8 b, VectorI8 c, VectorI8 d, int8_t* to) { hn::StoreInterleaved4(a, b, c, d, TagI8(), to); }

using TagI16 = hn::ScalableTag<int16_t>;
using VectorI16 = hn::VFromD<TagI16>;
using MaskI16 = hn::MFromD<TagI16>;
HWY_INLINE size_t laneCountI16() { return hn::Lanes(TagI16()); }
HWY_INLINE VectorI16 zeroI16() { return hn::Zero(TagI16()); }
HWY_INLINE VectorI16 repeatingI16(int16_t value) { return hn::Set(TagI16(), value); }
HWY_INLINE VectorI16 iotaI16(int16_t value) { return hn::Iota(TagI16(), value); }
HWY_INLINE VectorI16 loadI16(const int16_t* from) { return hn::LoadU(TagI16(), from); }
HWY_INLINE VectorI16 loadAlignedI16(const int16_t* from) { return hn::Load(TagI16(), from); }
HWY_INLINE VectorI16 loadFirstI16(const int16_t* from, size_t count) { return hn::LoadN(TagI16(), from, count); }
HWY_INLINE void storeI16(VectorI16 a, int16_t* to) { hn::StoreU(a, TagI16(), to); }
HWY_INLINE void storeAlignedI16(VectorI16 a, int16_t* to) { hn::Store(a, TagI16(), to); }
HWY_INLINE void storeFirstI16(VectorI16 a, int16_t* to, size_t count) { hn::StoreN(a, TagI16(), to, count); }
HWY_INLINE VectorI16 addingI16(VectorI16 a, VectorI16 b) { return hn::Add(a, b); }
HWY_INLINE VectorI16 subtractingI16(VectorI16 a, VectorI16 b) { return hn::Sub(a, b); }
HWY_INLINE VectorI16 multiplyingI16(VectorI16 a, VectorI16 b) { return hn::Mul(a, b); }
HWY_INLINE VectorI16 minimumI16(VectorI16 a, VectorI16 b) { return hn::Min(a, b); }
HWY_INLINE VectorI16 maximumI16(VectorI16 a, VectorI16 b) { return hn::Max(a, b); }
HWY_INLINE VectorI16 negatedI16(VectorI16 a) { return hn::Neg(a); }
HWY_INLINE VectorI16 magnitudeI16(VectorI16 a) { return hn::Abs(a); }
HWY_INLINE VectorI16 saturatingAddingI16(VectorI16 a, VectorI16 b) { return hn::SaturatedAdd(a, b); }
HWY_INLINE VectorI16 saturatingSubtractingI16(VectorI16 a, VectorI16 b) { return hn::SaturatedSub(a, b); }
HWY_INLINE VectorI16 bitwiseAndI16(VectorI16 a, VectorI16 b) { return hn::And(a, b); }
HWY_INLINE VectorI16 bitwiseOrI16(VectorI16 a, VectorI16 b) { return hn::Or(a, b); }
HWY_INLINE VectorI16 bitwiseXorI16(VectorI16 a, VectorI16 b) { return hn::Xor(a, b); }
HWY_INLINE VectorI16 bitwiseNotI16(VectorI16 a) { return hn::Not(a); }
HWY_INLINE VectorI16 bitwiseAndNotI16(VectorI16 a, VectorI16 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorI16 shiftedLeftI16(VectorI16 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorI16 shiftedRightI16(VectorI16 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskI16 equalToI16(VectorI16 a, VectorI16 b) { return hn::Eq(a, b); }
HWY_INLINE MaskI16 notEqualToI16(VectorI16 a, VectorI16 b) { return hn::Ne(a, b); }
HWY_INLINE MaskI16 lessThanI16(VectorI16 a, VectorI16 b) { return hn::Lt(a, b); }
HWY_INLINE MaskI16 greaterThanI16(VectorI16 a, VectorI16 b) { return hn::Gt(a, b); }
HWY_INLINE VectorI16 selectingI16(MaskI16 mask, VectorI16 a, VectorI16 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorI16 selectingOrZeroI16(MaskI16 mask, VectorI16 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorI16 zeroingSelectedI16(MaskI16 mask, VectorI16 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskI16 firstLanesI16(size_t count) { return hn::FirstN(TagI16(), count); }
HWY_INLINE bool allTrueI16(MaskI16 mask) { return hn::AllTrue(TagI16(), mask); }
HWY_INLINE bool allFalseI16(MaskI16 mask) { return hn::AllFalse(TagI16(), mask); }
HWY_INLINE size_t trueCountI16(MaskI16 mask) { return hn::CountTrue(TagI16(), mask); }
HWY_INLINE intptr_t firstTrueIndexI16(MaskI16 mask) { return hn::FindFirstTrue(TagI16(), mask); }
HWY_INLINE int16_t sumI16(VectorI16 a) { return hn::ReduceSum(TagI16(), a); }
HWY_INLINE int16_t smallestI16(VectorI16 a) { return hn::ReduceMin(TagI16(), a); }
HWY_INLINE int16_t largestI16(VectorI16 a) { return hn::ReduceMax(TagI16(), a); }
HWY_INLINE int16_t firstLaneI16(VectorI16 a) { return hn::GetLane(a); }
HWY_INLINE VectorI16 reversedI16(VectorI16 a) { return hn::Reverse(TagI16(), a); }
HWY_INLINE void loadInterleaved2I16(const int16_t* from, VectorI16& v0, VectorI16& v1) { hn::LoadInterleaved2(TagI16(), from, v0, v1); }
HWY_INLINE void loadInterleaved3I16(const int16_t* from, VectorI16& v0, VectorI16& v1, VectorI16& v2) { hn::LoadInterleaved3(TagI16(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4I16(const int16_t* from, VectorI16& v0, VectorI16& v1, VectorI16& v2, VectorI16& v3) { hn::LoadInterleaved4(TagI16(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2I16(VectorI16 a, VectorI16 b, int16_t* to) { hn::StoreInterleaved2(a, b, TagI16(), to); }
HWY_INLINE void storeInterleaved3I16(VectorI16 a, VectorI16 b, VectorI16 c, int16_t* to) { hn::StoreInterleaved3(a, b, c, TagI16(), to); }
HWY_INLINE void storeInterleaved4I16(VectorI16 a, VectorI16 b, VectorI16 c, VectorI16 d, int16_t* to) { hn::StoreInterleaved4(a, b, c, d, TagI16(), to); }
HWY_INLINE VectorI16 loadWideningI8ToI16(const int8_t* from) { return hn::PromoteTo(TagI16(), hn::LoadU(hn::Rebind<int8_t, TagI16>(), from)); }
HWY_INLINE VectorI16 loadFirstWideningI8ToI16(const int8_t* from, size_t count) { return hn::PromoteTo(TagI16(), hn::LoadN(hn::Rebind<int8_t, TagI16>(), from, count)); }

using TagI32 = hn::ScalableTag<int32_t>;
using VectorI32 = hn::VFromD<TagI32>;
using MaskI32 = hn::MFromD<TagI32>;
HWY_INLINE size_t laneCountI32() { return hn::Lanes(TagI32()); }
HWY_INLINE VectorI32 zeroI32() { return hn::Zero(TagI32()); }
HWY_INLINE VectorI32 repeatingI32(int32_t value) { return hn::Set(TagI32(), value); }
HWY_INLINE VectorI32 iotaI32(int32_t value) { return hn::Iota(TagI32(), value); }
HWY_INLINE VectorI32 loadI32(const int32_t* from) { return hn::LoadU(TagI32(), from); }
HWY_INLINE VectorI32 loadAlignedI32(const int32_t* from) { return hn::Load(TagI32(), from); }
HWY_INLINE VectorI32 loadFirstI32(const int32_t* from, size_t count) { return hn::LoadN(TagI32(), from, count); }
HWY_INLINE void storeI32(VectorI32 a, int32_t* to) { hn::StoreU(a, TagI32(), to); }
HWY_INLINE void storeAlignedI32(VectorI32 a, int32_t* to) { hn::Store(a, TagI32(), to); }
HWY_INLINE void storeFirstI32(VectorI32 a, int32_t* to, size_t count) { hn::StoreN(a, TagI32(), to, count); }
HWY_INLINE VectorI32 addingI32(VectorI32 a, VectorI32 b) { return hn::Add(a, b); }
HWY_INLINE VectorI32 subtractingI32(VectorI32 a, VectorI32 b) { return hn::Sub(a, b); }
HWY_INLINE VectorI32 multiplyingI32(VectorI32 a, VectorI32 b) { return hn::Mul(a, b); }
HWY_INLINE VectorI32 minimumI32(VectorI32 a, VectorI32 b) { return hn::Min(a, b); }
HWY_INLINE VectorI32 maximumI32(VectorI32 a, VectorI32 b) { return hn::Max(a, b); }
HWY_INLINE VectorI32 negatedI32(VectorI32 a) { return hn::Neg(a); }
HWY_INLINE VectorI32 magnitudeI32(VectorI32 a) { return hn::Abs(a); }
HWY_INLINE VectorI32 bitwiseAndI32(VectorI32 a, VectorI32 b) { return hn::And(a, b); }
HWY_INLINE VectorI32 bitwiseOrI32(VectorI32 a, VectorI32 b) { return hn::Or(a, b); }
HWY_INLINE VectorI32 bitwiseXorI32(VectorI32 a, VectorI32 b) { return hn::Xor(a, b); }
HWY_INLINE VectorI32 bitwiseNotI32(VectorI32 a) { return hn::Not(a); }
HWY_INLINE VectorI32 bitwiseAndNotI32(VectorI32 a, VectorI32 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorI32 shiftedLeftI32(VectorI32 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorI32 shiftedRightI32(VectorI32 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskI32 equalToI32(VectorI32 a, VectorI32 b) { return hn::Eq(a, b); }
HWY_INLINE MaskI32 notEqualToI32(VectorI32 a, VectorI32 b) { return hn::Ne(a, b); }
HWY_INLINE MaskI32 lessThanI32(VectorI32 a, VectorI32 b) { return hn::Lt(a, b); }
HWY_INLINE MaskI32 greaterThanI32(VectorI32 a, VectorI32 b) { return hn::Gt(a, b); }
HWY_INLINE VectorI32 selectingI32(MaskI32 mask, VectorI32 a, VectorI32 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorI32 selectingOrZeroI32(MaskI32 mask, VectorI32 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorI32 zeroingSelectedI32(MaskI32 mask, VectorI32 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskI32 firstLanesI32(size_t count) { return hn::FirstN(TagI32(), count); }
HWY_INLINE bool allTrueI32(MaskI32 mask) { return hn::AllTrue(TagI32(), mask); }
HWY_INLINE bool allFalseI32(MaskI32 mask) { return hn::AllFalse(TagI32(), mask); }
HWY_INLINE size_t trueCountI32(MaskI32 mask) { return hn::CountTrue(TagI32(), mask); }
HWY_INLINE intptr_t firstTrueIndexI32(MaskI32 mask) { return hn::FindFirstTrue(TagI32(), mask); }
HWY_INLINE int32_t sumI32(VectorI32 a) { return hn::ReduceSum(TagI32(), a); }
HWY_INLINE int32_t smallestI32(VectorI32 a) { return hn::ReduceMin(TagI32(), a); }
HWY_INLINE int32_t largestI32(VectorI32 a) { return hn::ReduceMax(TagI32(), a); }
HWY_INLINE int32_t firstLaneI32(VectorI32 a) { return hn::GetLane(a); }
HWY_INLINE VectorI32 reversedI32(VectorI32 a) { return hn::Reverse(TagI32(), a); }
HWY_INLINE void loadInterleaved2I32(const int32_t* from, VectorI32& v0, VectorI32& v1) { hn::LoadInterleaved2(TagI32(), from, v0, v1); }
HWY_INLINE void loadInterleaved3I32(const int32_t* from, VectorI32& v0, VectorI32& v1, VectorI32& v2) { hn::LoadInterleaved3(TagI32(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4I32(const int32_t* from, VectorI32& v0, VectorI32& v1, VectorI32& v2, VectorI32& v3) { hn::LoadInterleaved4(TagI32(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2I32(VectorI32 a, VectorI32 b, int32_t* to) { hn::StoreInterleaved2(a, b, TagI32(), to); }
HWY_INLINE void storeInterleaved3I32(VectorI32 a, VectorI32 b, VectorI32 c, int32_t* to) { hn::StoreInterleaved3(a, b, c, TagI32(), to); }
HWY_INLINE void storeInterleaved4I32(VectorI32 a, VectorI32 b, VectorI32 c, VectorI32 d, int32_t* to) { hn::StoreInterleaved4(a, b, c, d, TagI32(), to); }
HWY_INLINE VectorI32 loadWideningI8ToI32(const int8_t* from) { return hn::PromoteTo(TagI32(), hn::LoadU(hn::Rebind<int8_t, TagI32>(), from)); }
HWY_INLINE VectorI32 loadWideningI16ToI32(const int16_t* from) { return hn::PromoteTo(TagI32(), hn::LoadU(hn::Rebind<int16_t, TagI32>(), from)); }
HWY_INLINE VectorI32 loadFirstWideningI8ToI32(const int8_t* from, size_t count) { return hn::PromoteTo(TagI32(), hn::LoadN(hn::Rebind<int8_t, TagI32>(), from, count)); }
HWY_INLINE VectorI32 loadFirstWideningI16ToI32(const int16_t* from, size_t count) { return hn::PromoteTo(TagI32(), hn::LoadN(hn::Rebind<int16_t, TagI32>(), from, count)); }

using TagI64 = hn::ScalableTag<int64_t>;
using VectorI64 = hn::VFromD<TagI64>;
using MaskI64 = hn::MFromD<TagI64>;
HWY_INLINE size_t laneCountI64() { return hn::Lanes(TagI64()); }
HWY_INLINE VectorI64 zeroI64() { return hn::Zero(TagI64()); }
HWY_INLINE VectorI64 repeatingI64(int64_t value) { return hn::Set(TagI64(), value); }
HWY_INLINE VectorI64 iotaI64(int64_t value) { return hn::Iota(TagI64(), value); }
HWY_INLINE VectorI64 loadI64(const int64_t* from) { return hn::LoadU(TagI64(), from); }
HWY_INLINE VectorI64 loadAlignedI64(const int64_t* from) { return hn::Load(TagI64(), from); }
HWY_INLINE VectorI64 loadFirstI64(const int64_t* from, size_t count) { return hn::LoadN(TagI64(), from, count); }
HWY_INLINE void storeI64(VectorI64 a, int64_t* to) { hn::StoreU(a, TagI64(), to); }
HWY_INLINE void storeAlignedI64(VectorI64 a, int64_t* to) { hn::Store(a, TagI64(), to); }
HWY_INLINE void storeFirstI64(VectorI64 a, int64_t* to, size_t count) { hn::StoreN(a, TagI64(), to, count); }
HWY_INLINE VectorI64 addingI64(VectorI64 a, VectorI64 b) { return hn::Add(a, b); }
HWY_INLINE VectorI64 subtractingI64(VectorI64 a, VectorI64 b) { return hn::Sub(a, b); }
HWY_INLINE VectorI64 multiplyingI64(VectorI64 a, VectorI64 b) { return hn::Mul(a, b); }
HWY_INLINE VectorI64 minimumI64(VectorI64 a, VectorI64 b) { return hn::Min(a, b); }
HWY_INLINE VectorI64 maximumI64(VectorI64 a, VectorI64 b) { return hn::Max(a, b); }
HWY_INLINE VectorI64 negatedI64(VectorI64 a) { return hn::Neg(a); }
HWY_INLINE VectorI64 magnitudeI64(VectorI64 a) { return hn::Abs(a); }
HWY_INLINE VectorI64 bitwiseAndI64(VectorI64 a, VectorI64 b) { return hn::And(a, b); }
HWY_INLINE VectorI64 bitwiseOrI64(VectorI64 a, VectorI64 b) { return hn::Or(a, b); }
HWY_INLINE VectorI64 bitwiseXorI64(VectorI64 a, VectorI64 b) { return hn::Xor(a, b); }
HWY_INLINE VectorI64 bitwiseNotI64(VectorI64 a) { return hn::Not(a); }
HWY_INLINE VectorI64 bitwiseAndNotI64(VectorI64 a, VectorI64 b) { return hn::AndNot(a, b); }
HWY_INLINE VectorI64 shiftedLeftI64(VectorI64 a, int bits) { return hn::ShiftLeftSame(a, bits); }
HWY_INLINE VectorI64 shiftedRightI64(VectorI64 a, int bits) { return hn::ShiftRightSame(a, bits); }
HWY_INLINE MaskI64 equalToI64(VectorI64 a, VectorI64 b) { return hn::Eq(a, b); }
HWY_INLINE MaskI64 notEqualToI64(VectorI64 a, VectorI64 b) { return hn::Ne(a, b); }
HWY_INLINE MaskI64 lessThanI64(VectorI64 a, VectorI64 b) { return hn::Lt(a, b); }
HWY_INLINE MaskI64 greaterThanI64(VectorI64 a, VectorI64 b) { return hn::Gt(a, b); }
HWY_INLINE VectorI64 selectingI64(MaskI64 mask, VectorI64 a, VectorI64 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorI64 selectingOrZeroI64(MaskI64 mask, VectorI64 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorI64 zeroingSelectedI64(MaskI64 mask, VectorI64 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskI64 firstLanesI64(size_t count) { return hn::FirstN(TagI64(), count); }
HWY_INLINE bool allTrueI64(MaskI64 mask) { return hn::AllTrue(TagI64(), mask); }
HWY_INLINE bool allFalseI64(MaskI64 mask) { return hn::AllFalse(TagI64(), mask); }
HWY_INLINE size_t trueCountI64(MaskI64 mask) { return hn::CountTrue(TagI64(), mask); }
HWY_INLINE intptr_t firstTrueIndexI64(MaskI64 mask) { return hn::FindFirstTrue(TagI64(), mask); }
HWY_INLINE int64_t sumI64(VectorI64 a) { return hn::ReduceSum(TagI64(), a); }
HWY_INLINE int64_t smallestI64(VectorI64 a) { return hn::ReduceMin(TagI64(), a); }
HWY_INLINE int64_t largestI64(VectorI64 a) { return hn::ReduceMax(TagI64(), a); }
HWY_INLINE int64_t firstLaneI64(VectorI64 a) { return hn::GetLane(a); }
HWY_INLINE VectorI64 reversedI64(VectorI64 a) { return hn::Reverse(TagI64(), a); }
HWY_INLINE void loadInterleaved2I64(const int64_t* from, VectorI64& v0, VectorI64& v1) { hn::LoadInterleaved2(TagI64(), from, v0, v1); }
HWY_INLINE void loadInterleaved3I64(const int64_t* from, VectorI64& v0, VectorI64& v1, VectorI64& v2) { hn::LoadInterleaved3(TagI64(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4I64(const int64_t* from, VectorI64& v0, VectorI64& v1, VectorI64& v2, VectorI64& v3) { hn::LoadInterleaved4(TagI64(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2I64(VectorI64 a, VectorI64 b, int64_t* to) { hn::StoreInterleaved2(a, b, TagI64(), to); }
HWY_INLINE void storeInterleaved3I64(VectorI64 a, VectorI64 b, VectorI64 c, int64_t* to) { hn::StoreInterleaved3(a, b, c, TagI64(), to); }
HWY_INLINE void storeInterleaved4I64(VectorI64 a, VectorI64 b, VectorI64 c, VectorI64 d, int64_t* to) { hn::StoreInterleaved4(a, b, c, d, TagI64(), to); }
HWY_INLINE VectorI64 loadWideningI8ToI64(const int8_t* from) { return hn::PromoteTo(TagI64(), hn::LoadU(hn::Rebind<int8_t, TagI64>(), from)); }
HWY_INLINE VectorI64 loadWideningI16ToI64(const int16_t* from) { return hn::PromoteTo(TagI64(), hn::LoadU(hn::Rebind<int16_t, TagI64>(), from)); }
HWY_INLINE VectorI64 loadWideningI32ToI64(const int32_t* from) { return hn::PromoteTo(TagI64(), hn::LoadU(hn::Rebind<int32_t, TagI64>(), from)); }
HWY_INLINE VectorI64 loadFirstWideningI8ToI64(const int8_t* from, size_t count) { return hn::PromoteTo(TagI64(), hn::LoadN(hn::Rebind<int8_t, TagI64>(), from, count)); }
HWY_INLINE VectorI64 loadFirstWideningI16ToI64(const int16_t* from, size_t count) { return hn::PromoteTo(TagI64(), hn::LoadN(hn::Rebind<int16_t, TagI64>(), from, count)); }
HWY_INLINE VectorI64 loadFirstWideningI32ToI64(const int32_t* from, size_t count) { return hn::PromoteTo(TagI64(), hn::LoadN(hn::Rebind<int32_t, TagI64>(), from, count)); }

using TagF32 = hn::ScalableTag<float>;
using VectorF32 = hn::VFromD<TagF32>;
using MaskF32 = hn::MFromD<TagF32>;
HWY_INLINE size_t laneCountF32() { return hn::Lanes(TagF32()); }
HWY_INLINE VectorF32 zeroF32() { return hn::Zero(TagF32()); }
HWY_INLINE VectorF32 repeatingF32(float value) { return hn::Set(TagF32(), value); }
HWY_INLINE VectorF32 iotaF32(float value) { return hn::Iota(TagF32(), value); }
HWY_INLINE VectorF32 loadF32(const float* from) { return hn::LoadU(TagF32(), from); }
HWY_INLINE VectorF32 loadAlignedF32(const float* from) { return hn::Load(TagF32(), from); }
HWY_INLINE VectorF32 loadFirstF32(const float* from, size_t count) { return hn::LoadN(TagF32(), from, count); }
HWY_INLINE void storeF32(VectorF32 a, float* to) { hn::StoreU(a, TagF32(), to); }
HWY_INLINE void storeAlignedF32(VectorF32 a, float* to) { hn::Store(a, TagF32(), to); }
HWY_INLINE void storeFirstF32(VectorF32 a, float* to, size_t count) { hn::StoreN(a, TagF32(), to, count); }
HWY_INLINE VectorF32 addingF32(VectorF32 a, VectorF32 b) { return hn::Add(a, b); }
HWY_INLINE VectorF32 subtractingF32(VectorF32 a, VectorF32 b) { return hn::Sub(a, b); }
HWY_INLINE VectorF32 multiplyingF32(VectorF32 a, VectorF32 b) { return hn::Mul(a, b); }
HWY_INLINE VectorF32 dividingF32(VectorF32 a, VectorF32 b) { return hn::Div(a, b); }
HWY_INLINE VectorF32 minimumF32(VectorF32 a, VectorF32 b) { return hn::Min(a, b); }
HWY_INLINE VectorF32 maximumF32(VectorF32 a, VectorF32 b) { return hn::Max(a, b); }
HWY_INLINE VectorF32 negatedF32(VectorF32 a) { return hn::Neg(a); }
HWY_INLINE VectorF32 magnitudeF32(VectorF32 a) { return hn::Abs(a); }
HWY_INLINE VectorF32 squareRootF32(VectorF32 a) { return hn::Sqrt(a); }
HWY_INLINE VectorF32 multiplyAddingF32(VectorF32 a, VectorF32 b, VectorF32 c) { return hn::MulAdd(a, b, c); }
HWY_INLINE MaskF32 equalToF32(VectorF32 a, VectorF32 b) { return hn::Eq(a, b); }
HWY_INLINE MaskF32 notEqualToF32(VectorF32 a, VectorF32 b) { return hn::Ne(a, b); }
HWY_INLINE MaskF32 lessThanF32(VectorF32 a, VectorF32 b) { return hn::Lt(a, b); }
HWY_INLINE MaskF32 greaterThanF32(VectorF32 a, VectorF32 b) { return hn::Gt(a, b); }
HWY_INLINE VectorF32 selectingF32(MaskF32 mask, VectorF32 a, VectorF32 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorF32 selectingOrZeroF32(MaskF32 mask, VectorF32 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorF32 zeroingSelectedF32(MaskF32 mask, VectorF32 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskF32 firstLanesF32(size_t count) { return hn::FirstN(TagF32(), count); }
HWY_INLINE bool allTrueF32(MaskF32 mask) { return hn::AllTrue(TagF32(), mask); }
HWY_INLINE bool allFalseF32(MaskF32 mask) { return hn::AllFalse(TagF32(), mask); }
HWY_INLINE size_t trueCountF32(MaskF32 mask) { return hn::CountTrue(TagF32(), mask); }
HWY_INLINE intptr_t firstTrueIndexF32(MaskF32 mask) { return hn::FindFirstTrue(TagF32(), mask); }
HWY_INLINE float sumF32(VectorF32 a) { return hn::ReduceSum(TagF32(), a); }
HWY_INLINE float smallestF32(VectorF32 a) { return hn::ReduceMin(TagF32(), a); }
HWY_INLINE float largestF32(VectorF32 a) { return hn::ReduceMax(TagF32(), a); }
HWY_INLINE float firstLaneF32(VectorF32 a) { return hn::GetLane(a); }
HWY_INLINE VectorF32 reversedF32(VectorF32 a) { return hn::Reverse(TagF32(), a); }
HWY_INLINE void loadInterleaved2F32(const float* from, VectorF32& v0, VectorF32& v1) { hn::LoadInterleaved2(TagF32(), from, v0, v1); }
HWY_INLINE void loadInterleaved3F32(const float* from, VectorF32& v0, VectorF32& v1, VectorF32& v2) { hn::LoadInterleaved3(TagF32(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4F32(const float* from, VectorF32& v0, VectorF32& v1, VectorF32& v2, VectorF32& v3) { hn::LoadInterleaved4(TagF32(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2F32(VectorF32 a, VectorF32 b, float* to) { hn::StoreInterleaved2(a, b, TagF32(), to); }
HWY_INLINE void storeInterleaved3F32(VectorF32 a, VectorF32 b, VectorF32 c, float* to) { hn::StoreInterleaved3(a, b, c, TagF32(), to); }
HWY_INLINE void storeInterleaved4F32(VectorF32 a, VectorF32 b, VectorF32 c, VectorF32 d, float* to) { hn::StoreInterleaved4(a, b, c, d, TagF32(), to); }

using TagF64 = hn::ScalableTag<double>;
using VectorF64 = hn::VFromD<TagF64>;
using MaskF64 = hn::MFromD<TagF64>;
HWY_INLINE size_t laneCountF64() { return hn::Lanes(TagF64()); }
HWY_INLINE VectorF64 zeroF64() { return hn::Zero(TagF64()); }
HWY_INLINE VectorF64 repeatingF64(double value) { return hn::Set(TagF64(), value); }
HWY_INLINE VectorF64 iotaF64(double value) { return hn::Iota(TagF64(), value); }
HWY_INLINE VectorF64 loadF64(const double* from) { return hn::LoadU(TagF64(), from); }
HWY_INLINE VectorF64 loadAlignedF64(const double* from) { return hn::Load(TagF64(), from); }
HWY_INLINE VectorF64 loadFirstF64(const double* from, size_t count) { return hn::LoadN(TagF64(), from, count); }
HWY_INLINE void storeF64(VectorF64 a, double* to) { hn::StoreU(a, TagF64(), to); }
HWY_INLINE void storeAlignedF64(VectorF64 a, double* to) { hn::Store(a, TagF64(), to); }
HWY_INLINE void storeFirstF64(VectorF64 a, double* to, size_t count) { hn::StoreN(a, TagF64(), to, count); }
HWY_INLINE VectorF64 addingF64(VectorF64 a, VectorF64 b) { return hn::Add(a, b); }
HWY_INLINE VectorF64 subtractingF64(VectorF64 a, VectorF64 b) { return hn::Sub(a, b); }
HWY_INLINE VectorF64 multiplyingF64(VectorF64 a, VectorF64 b) { return hn::Mul(a, b); }
HWY_INLINE VectorF64 dividingF64(VectorF64 a, VectorF64 b) { return hn::Div(a, b); }
HWY_INLINE VectorF64 minimumF64(VectorF64 a, VectorF64 b) { return hn::Min(a, b); }
HWY_INLINE VectorF64 maximumF64(VectorF64 a, VectorF64 b) { return hn::Max(a, b); }
HWY_INLINE VectorF64 negatedF64(VectorF64 a) { return hn::Neg(a); }
HWY_INLINE VectorF64 magnitudeF64(VectorF64 a) { return hn::Abs(a); }
HWY_INLINE VectorF64 squareRootF64(VectorF64 a) { return hn::Sqrt(a); }
HWY_INLINE VectorF64 multiplyAddingF64(VectorF64 a, VectorF64 b, VectorF64 c) { return hn::MulAdd(a, b, c); }
HWY_INLINE MaskF64 equalToF64(VectorF64 a, VectorF64 b) { return hn::Eq(a, b); }
HWY_INLINE MaskF64 notEqualToF64(VectorF64 a, VectorF64 b) { return hn::Ne(a, b); }
HWY_INLINE MaskF64 lessThanF64(VectorF64 a, VectorF64 b) { return hn::Lt(a, b); }
HWY_INLINE MaskF64 greaterThanF64(VectorF64 a, VectorF64 b) { return hn::Gt(a, b); }
HWY_INLINE VectorF64 selectingF64(MaskF64 mask, VectorF64 a, VectorF64 b) { return hn::IfThenElse(mask, a, b); }
HWY_INLINE VectorF64 selectingOrZeroF64(MaskF64 mask, VectorF64 a) { return hn::IfThenElseZero(mask, a); }
HWY_INLINE VectorF64 zeroingSelectedF64(MaskF64 mask, VectorF64 a) { return hn::IfThenZeroElse(mask, a); }
HWY_INLINE MaskF64 firstLanesF64(size_t count) { return hn::FirstN(TagF64(), count); }
HWY_INLINE bool allTrueF64(MaskF64 mask) { return hn::AllTrue(TagF64(), mask); }
HWY_INLINE bool allFalseF64(MaskF64 mask) { return hn::AllFalse(TagF64(), mask); }
HWY_INLINE size_t trueCountF64(MaskF64 mask) { return hn::CountTrue(TagF64(), mask); }
HWY_INLINE intptr_t firstTrueIndexF64(MaskF64 mask) { return hn::FindFirstTrue(TagF64(), mask); }
HWY_INLINE double sumF64(VectorF64 a) { return hn::ReduceSum(TagF64(), a); }
HWY_INLINE double smallestF64(VectorF64 a) { return hn::ReduceMin(TagF64(), a); }
HWY_INLINE double largestF64(VectorF64 a) { return hn::ReduceMax(TagF64(), a); }
HWY_INLINE double firstLaneF64(VectorF64 a) { return hn::GetLane(a); }
HWY_INLINE VectorF64 reversedF64(VectorF64 a) { return hn::Reverse(TagF64(), a); }
HWY_INLINE void loadInterleaved2F64(const double* from, VectorF64& v0, VectorF64& v1) { hn::LoadInterleaved2(TagF64(), from, v0, v1); }
HWY_INLINE void loadInterleaved3F64(const double* from, VectorF64& v0, VectorF64& v1, VectorF64& v2) { hn::LoadInterleaved3(TagF64(), from, v0, v1, v2); }
HWY_INLINE void loadInterleaved4F64(const double* from, VectorF64& v0, VectorF64& v1, VectorF64& v2, VectorF64& v3) { hn::LoadInterleaved4(TagF64(), from, v0, v1, v2, v3); }
HWY_INLINE void storeInterleaved2F64(VectorF64 a, VectorF64 b, double* to) { hn::StoreInterleaved2(a, b, TagF64(), to); }
HWY_INLINE void storeInterleaved3F64(VectorF64 a, VectorF64 b, VectorF64 c, double* to) { hn::StoreInterleaved3(a, b, c, TagF64(), to); }
HWY_INLINE void storeInterleaved4F64(VectorF64 a, VectorF64 b, VectorF64 c, VectorF64 d, double* to) { hn::StoreInterleaved4(a, b, c, d, TagF64(), to); }
HWY_INLINE VectorF64 loadWideningF32ToF64(const float* from) { return hn::PromoteTo(TagF64(), hn::LoadU(hn::Rebind<float, TagF64>(), from)); }
HWY_INLINE VectorF64 loadFirstWideningF32ToF64(const float* from, size_t count) { return hn::PromoteTo(TagF64(), hn::LoadN(hn::Rebind<float, TagF64>(), from, count)); }

}  // namespace HighwayOps

#endif
